<?php


return [



    /**
     * saml storage path used for storing files generated by Raftalks\SAML libary
    */

    'disk' => [
        'driver' => 'local',
        'pathname' => 'saml',
    ]

];